{% set version = "1.1.0" %}

package:
  name: mpc
  version: {{ version }}

source:
  fn: mpc-{{ version }}.tar.gz                                              # [unix]
  url: http://www.multiprecision.org/mpc/download/mpc-{{ version }}.tar.gz  # [unix]
  sha256: 6985c538143c1208dcb1ac42cedad6ff52e267b47e5f970183a3e75125b43c2e  # [unix]
  fn: mpc-{{ version }}.zip                                                 # [win]
  url: https://github.com/saraedum/mpc/archive/v{{ version }}.zip           # [win]
  sha256: e5d4f2af1988f371837f7a7a7f27d7589ed19dadf21d9639f58bb3ec2a867e7f  # [win]

build:
  number: 4
  features:
    - vc14            # [win]
  msvc_compiler: 14.0

requirements:
  build:
    - toolchain
    - m4              # [unix]
    - libtool         # [unix]
    - gmp >=5.0.1,<7  # [unix]
    - mpir            # [win]
    - mpfr 3.*
  run:
    - gmp >=5.0.1,<7  # [unix]
    - mpir            # [win]
    - vc 14           # [win]
    - mpfr 3.*

test:
  commands:
    - if not exist %LIBRARY_INC%\\mpc.h exit 1                  # [win]
    - if not exist %LIBRARY_LIB%\\mpc.lib exit 1                # [win]
    - if not exist %LIBRARY_BIN%\\mpc.dll exit 1                # [win]
    - if not exist %LIBRARY_LIB%\\mpc_static.lib exit 1         # [win]
    - test -f ${PREFIX}/include/mpc.h                           # [unix]
    - test -f ${PREFIX}/lib/libmpc.a                            # [unix]
    - test -f ${PREFIX}/lib/libmpc.dylib                        # [osx]
    - test -f ${PREFIX}/lib/libmpc.so                           # [linux]

about:
  home: http://www.multiprecision.org/
  license: LGPL 3
  license_file: {{ SRC_DIR }}/COPYING.LESSER
  summary: A C library for the arithmetic of complex numbers with arbitrarily high precision.

extra:
  recipe-maintainers:
    - isuruf
    - jakirkham
    - saraedum
