travis:
  secure:
    BINSTAR_TOKEN: ektzAjZME+jVPjwSqQxNGL/PYkVbcpF9cOPp66QMY318ukIBhhzDX1n6fHC2QYBnY6ujQd3tFIOdwq+39kDmCefqxR1M3k7yP6nfx/YTGjQ2+NLbuXAjoaL28/STfiD036YSFQSNi7/xsaYmVx3Rb3xpHuwNKhodExrrQJRUniqsT5MuJRePhcG+/pmvGcofLusaEtN0Tagh2VMIr1QBMmOZmQZ6vbRCpgAUv88Qrev7LPsE5IlWxn+is7PrqxEE6Y0yydmQxGE7+dsnrFNgx6hJdD71//a0Up+qPVD5867Ud257ao+vxLi+iOkDGuOsmUVc+TPoqdg7W4N91WQxUdOH2v42glE9mJy8W7rAlaVdCz93zP2E5cilQeTYOlg7ok5rav/fmTgVUTUSRqdWAQahAlfHU2qtDrv2HTeYXaDg/kouuFONRq/CEukrPTkb12Bd7APdRF6V4n+qqXYeaz9JpgEyyuzDk5Ubd27KFFOI1UArO7nDV/eJM7vBzKWBY+YB7tQrG3gvSKrcCzvOGnAQQJtWT5y2ppjlYkBiuVAAqklcLrG5A+wo0h/a1BlwPem1wy4iLdoRpTVqjwVcZfjq2iKGP4f5ErfGEh/uQ498fir/Xo8a6GkdldMTes/cz6qDNb3HgH4mTzGnG2QRjZh16BTYbHFjfSgHICmUHts=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
