travis:
  secure:
    BINSTAR_TOKEN: 5TxJ6UZ42lRbc6R3p3KO41u7XP+ZjUBwiEy5dfv12xDfizWL/lw8WVLv6nGpN3phYfBRBjYGK638dV5HFSEBDZfZTyKJz6ex7vpa15UVpsLIvtUrBItVUsCvj6RGllpPXPGi917QXB6bPynLQqLXvwew1b+Tnu+65VLuZOFAuOdTbr7Xk0Njeg27dyqWUrEcJJV/MyU3cqK4Jg492ssShSAjAu4cB3tg2Vqp/ZluJ5lPTtMNZD9Yfd7+W8b955tu5momLL1Nxi7wJmN6OBPxT14/t+A0vZTkcrSkCtdAcvsrbpS5Gn0HAKFrb/zvcMerPdtzCNM68YNqPglZQYpbITN2rFelKpTtm4pEZfgajswDvXz17XPn5ICJFdH02eg21eORDVR1QX/cdjhnrAR2/jeaKDyj1BhodQOC8I9yCmedG4J88H0A/vAXbpt5x6hc1Mq5NooGUibGyh4xJLgceXov3X7YY8oQmD2CKvROO1rLVe5KXYycYNgFQGOykN7IEH0Ri5gCNI0A4UCXXJo1merk34MCWHLb0LnwhWxqfIHIgjNWhcKNH4LE0Yn2D54gD6u2ntKJIzM2fujytR3/Kd6sdclVHJmzy7LG46dTtGm46warO38DJhx/fRj3Gs6bzf3o/pak3UvQSu1Qws1qDHaPS9e34xniear0BuZBj+8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
